### ISSUE TITLE
forked from NRasterizer

### ISSUE THREAD

**Issue by prepare** [prepare/FontRasterizer#1]
Thank you @vidstige 
I forked this from your https://github.com/vidstige/NRasterizer.
because I don't want to make your github 'network' graph look mess, while I am modifying it.

my goals:
1.  use the OpenType Reader to read .ttf
2.  render it with the PixelFarm. (we have anti-alias quality software/hardware renderer)

**Comment by vidstige** [comment]
Sounds great! Perhaps we can make it so you can plug in different renderers. I want to also keep the software renderer for various reasons. Can PixelFarm fill paths? Basically all the glyphs are paths in the end consisting of bezier and straight parts.

**Comment by vidstige** [comment]
This will still show up in the network graph, but that's fine. In fact, forking is the way to contribute to NRasterizer. :+1:

**Comment by prepare** [comment]
@vidstige , 
This is a result :)
Thank you for your OpenType Reader 👍 

![](https://raw.githubusercontent.com/prepare/FontRasterizer/master/screenshots/2.png)

**Comment by vidstige** [comment]
Oh, cool! :-) Thanks. I'll check out the code right away. If I've got time I can try to separate out the loading parts, etc more clearly. :+1:

**Comment by vidstige** [comment]
One more think, there is one bug in the parsing of contour points. I think lower case "a" for example shows this when using whatever font I used as default in the sample UI.

**Comment by prepare** [comment]
@larsbrubaker,
I want to say thank you for your agg-sharp lib 👍 
I use the modified version (PixelFarm) to render OpenType font with pure C# !
if you are interested, please visit https://github.com/prepare/FontRasterizer.

I think you can integreate the OpenType reader logic to your agg-sharp lib too :)

win

**Comment by prepare** [comment]
this lower case 'a' ?

![](https://raw.githubusercontent.com/prepare/FontRasterizer/12780650284fb7df3cf3a7a87b422de117f682f7/screenshots/4.png)

**Comment by vidstige** [comment]
hmm.. I think it was another font. Maybe I fixed it acutally without remembering...

**Comment by larsbrubaker** [comment]
Thank you for showing this to my and all your work. This could be useful in
some of our work to load up ttfs.

Nice job.

**Comment by prepare** [comment]
update screen-shoots
glyph render compare with the one from Windows's Notepad
at the same size

72 pts
![font_compare1](https://cloud.githubusercontent.com/assets/7447159/19414301/597e7b82-9372-11e6-81b8-5c8374a7400d.png)

8 pts 
![font_compare2](https://cloud.githubusercontent.com/assets/7447159/19414345/de616836-9373-11e6-87ac-64076a8d9f1c.png)

**Comment by prepare** [comment]
The quick brown fox jumps over the lazy dog,

Tahoma, 11 pts
![font_compare3](https://cloud.githubusercontent.com/assets/7447159/19414753/bec50254-9381-11e6-8ebb-07b23d84eb90.png)

**Comment by prepare** [comment]
enable kerning
![font_compare4_kern](https://cloud.githubusercontent.com/assets/7447159/19415069/d938e216-938d-11e6-82f1-6617e9c5e866.png)

**Comment by vidstige** [comment]
Nice! :-) I think the two repos have diverged too much now. I keep working in the NRasterier repo instead.

**Comment by prepare** [comment]
@vidstige  

sorry about that.
the time is comming,
the HtmlRenderer must be completed soon.

so what I have changed in
the FontRasterizer is based on
what it will be integrated with the
PixelFarm and HtmlRenderer.

please  think  of this repo,
this will be just a playground.
some code are just designed, quick and dirty.

1.  I will try to do a pull request for you too.
     for bug, idea etc
2.  If some design is sattled, I will ask you for comments
3.  for me, now the GSUB table must complete soon.
     it need for me to render properly.

Thank you very much
:)

**Comment by vidstige** [comment]
I understand, I also like to complete fast. But for this abstract base class for example. If you undo that part, you can just merge kern and GSUB table loading into master without problems.... So in fact that only makes things take longer time.

**Comment by vidstige** [comment]
I can see if I can make a pull request to your repo soon. I'm just going to eat breakfast first. :-)

**Comment by prepare** [comment]
Umm...
I love interface,
but why don't you like an abstract class ?

**Comment by vidstige** [comment]
You want the long story or the short story? :-) I have nothing against abstract classes, but it usually ends up coupling the interface with the implementation. In case of the renderer or "glyph builder" you had one part of the class that was interface and one part that was renderer. 

Having an interface makes it easier to implement other classes of this interface. What if, for example you need to subclass to draw pixels in a framework? If it is just an interface, it's easy, but you cannot inherit from two classes. Just one small example. I've worked with c# from 2007-2013.

**Comment by vidstige** [comment]
I will also rename the `GlyphPathBuilderBase` first now.

**Comment by prepare** [comment]
for me...
**Abstract class:**
I  use abstract for
   a  group of  closely related classes,
   the class in the group has different only some behaviors,
   or interfaces (property/method)
   and they are designed to be deep hierarchy of  inheritance.
  
   I use abstract method in an abstract class, as a mechanism
   of control some must-implement-behaviors.
   (like interface)

   for examples:
        BirdBase
               BirdA, BirdB, BirdC etc
        

**Interface**
I use interface for
    control some loose-coupling classes,
    reduce coupling. 
    those object are not the same thing in its original nature.
   but they need to have some thing the same. 

   umm... multiple facets/ multiple  
   
 for examples:
       interface IPaperOffice {}
            OfficeA: IOffice, IPaperOffice
            Home: IPaperOffce,
            TrainStattion: IPaperOffice
       like that..

**Comment by vidstige** [comment]
Yes, exactly. In reality then loose couple is usually to prefer. There is rarely any reason to have higher coupling between classes. In this specific case of the tables, they do not even have to have either an interface nor abstract class. Instead they could just have a header property if you wanted to lookup the name or such.

In any event, if you simply add the table loading code without refactoring to abstract class I'll gladly merge right away. Otherwise I'm very far from convinced.

**Comment by prepare** [comment]
Thank you, I love study too, If you have more information please let me know.

> In case of the renderer or "glyph builder" you had one part of the class that was interface and one part that was renderer

for the GlyphPathBuilderVxs, that is the original intention of class
see https://github.com/prepare/FontRasterizer/blob/master/FontRasterizerSample.WinForms/GlyphPathBuilderVxs.cs

It just produces a vertex store (vxs) (as the name VertextBuilder)
that will be used in next state.
(eg  transformed,and send to OpenGL backend), 
no rendering occurs here.


But I agree that my (quick and dirty)
example GlyphPathBuilderGdiPlus make it look bad.
because it bundles the rendering part. :(

**Comment by vidstige** [comment]
But how do you feel about the `IGlyphRasterizer`? I feel it's a great interface that _only_ contains the functions needed to render. Whether it is to a vertex-buffer or System.Drawing or my software rasterizer. Also the name clearly state what it does: rasterizes (turns vector graphics into pixels) glyphs.

**Comment by prepare** [comment]
>  In this specific case of the tables, they do not even have to have either an interface nor abstract class. Instead they could just have a header property if you wanted to lookup the name or such.

see: https://github.com/prepare/FontRasterizer/blob/master/OpenTypeReader/OpenTypeReader.cs#L64
and
see https://github.com/prepare/FontRasterizer/issues/3

That's what I use the nature of an abstract class, to force that
every table need to implement ReadContentFrom()  
 
see:
https://github.com/prepare/FontRasterizer/blob/master/OpenTypeReader/OpenTypeReader.cs#L92

dose it look simple?

If you not choose abstract/ interface.
then you must to check the method name every time.
you have no mechanism to control that
in the same type of class, method must be the same.
it's easy to find reference of all related methods. (right-click...)

In this case,(not use abstract/interface)
you may have 
    ReadContentFrom() 
    ReadContentfrom(),
    Readcontentfrom(),

dose it look headache ?

**Comment by prepare** [comment]
> But how do you feel about the IGlyphRasterizer? I feel it's a great interface that only contains the functions needed to render

In this case, It's great.
I integrate that into a repo.
see https://github.com/prepare/FontRasterizer/blob/master/OpenTypeReader/GlyphPathBuilder.cs

and I 've removed the my old bad one (GlyphPathBuilderGdiPlus).

**Comment by vidstige** [comment]
[Here](https://github.com/vidstige/NRasterizer/blob/master/NOpenType/OpenTypeReader.cs#L40) is the alternative:

In fact it's the other way around, when you navigate in current master with e.g. F12 you will end up at the correct implmentation, while if you have an abstract base class (or even interface) you will just end up there instead!

The tables have no common interface. The only thing they have in common is how they are _instantiated_. Then you could have an abstract `TableBuilder` or something like that, but why complicate things? Instead try to make things as simple as possible, in this case see the link above how you can make this very very simple. That's all the code there is. :-)

**Comment by vidstige** [comment]
A great. I just renamed it to `Renderer` short and plain in master as well.

**Comment by prepare** [comment]
But the GlyphPathBuilderVxs, still exists,
because it is exact the vertex builder /PathBuilder. 

What do you do for that case,
do I need to implement an IGlyphRasterizer class
to do something about PathBuilder

**Comment by vidstige** [comment]
Yes you still need `GlyphPathBuilderVxs`, but I would just rename it to `AggRenderer` or something. Or if it doesnot actually render go for `AggVertexBufferRenderer` or smilar.

**Comment by vidstige** [comment]
To an unrelated issue, my character gets drawn upside down now. :-) How do you handle that in your repo? I think I'll need to use the base-line or something like that.

One more thing I need to change: I will use integer math until the very last step when things get passed to rasterizer. This is to get infinite precision.

**Comment by prepare** [comment]
VertexStore is just a vertex buffer (the vxs- vertex store).
the buffer can send to matrix operation of both software-based 
and hardware-based backend.

but It's originate from Agg lib.

**Comment by vidstige** [comment]
Again, I would just go with `AggVertexBufferRenderer` then.

**Comment by prepare** [comment]
> my character gets drawn upside down now. :-) 
How do you handle that in your repo?
 I think I'll need to use the base-line or something like that.

do you have an image of that?
font data is upside down in nature.
(x,y) is at left lower corner

so in Gdi+, I flip it.
 see https://github.com/prepare/FontRasterizer/blob/master/FontRasterizerSample.WinForms/Form1.cs#L195

but for the MiniAgg,
Its ok, it based on what canvas do.

**Comment by vidstige** [comment]
Yes, it is stored upside down in the font file. I think perhaps it would make more sense to handle this in the `Renderer`. There we also have access to baseline information, etc. Then you would need to flip inside Agg renderer instead. Ok?

**Comment by prepare** [comment]
> Again, I would just go with AggVertexBufferRenderer then.

In my thought,
1.  I think render may send some thing visual graphics look,
   like 'Render on OpenGL'. a big picture.

2. Raster, is more specific term about  putting a pixel into  a scanline.

so If you mean 'Renderer' is for render vertex?

**Comment by prepare** [comment]
> One more thing I need to change: I will use integer math until the very last step when things get passed to rasterizer. This is to get infinite precision.

Yes, I see that, I've already changed it.
see:  
https://github.com/prepare/FontRasterizer/blob/master/OpenTypeReader/GlyphPathBuilderBase.cs#L35

and that support exact font size look (as in the picture above).

**Comment by prepare** [comment]
> Yes, it is stored upside down in the font file. I think perhaps it would make more sense to handle this in the Renderer. There we also have access to baseline information, etc. Then you would need to flip inside Agg renderer instead. Ok?

The upside-down font is OK for me :)
It reflects the nature!

**Comment by vidstige** [comment]
1. Yes, I think render is sufficent? Perhaps there is a even better name. Do you have any suggestions?
2. Ok, great. I feel us two editing the two repos as the same time is very confusing.... I'll make a pull request to use NuGet package instead right now.
3. Great! :)

**Comment by prepare** [comment]
anyway,
I have some tasks to do now
(not on the computer),
I will be back in 1-2 hours.

**Comment by prepare** [comment]
> I think render is sufficent? Perhaps there is a even better name. Do you have any suggestions

I try to use the consistent name across 
other repos (HtmlRenderer and PixelFarm),

such as Render, Raster as describe above,

so in this case, I think the class's job is to generate vertex,
Its name should be such as

GlyphVertextGenerator,
GlyphVertextCreator,
GlyphVertextBuilder,

...

**Comment by vidstige** [comment]
Name sounds great. Hmm, but now you expose things outside the Renderer class such as `GetFUnitToPixelsScale`. This does not seem clean to me. I'll make my own int renderer code.

**Comment by prepare** [comment]
yes, that is a dirty code.
the value can be calculate in other place.
